all.out:circle.h test_circle.cpp rectangle.h test_rectangle.cpp triangle.h test_triangle.cpp
	g++ circle.h test_circle.cpp rectangle.h test_rectangle.cpp triangle.h test_triangle.cpp -lgtest_main -lgtest -lpthread -o all.out
test:
	./all.out
clean:
	rm *.out
